print("       ________________")
print("       |  /          |")
print("       | /           |")
print("       |/            |")
print("       |           __|__")
print("       |          /     \\")
print("       |         |       |")
print("       |          \\_____/")
print("       |             |")
print("       |          \\  |  /")
print("       |           \\ | /")
print("       |            \\|/")
print("       |             |")
print("       |             |")
print("       |            /|\\")
print("       |           /   \\")
print("       |          /     \\")
print("       |         /       \\")
print("       |        /         \\")
print("       |")
print("       |")
print("       |")
print("      / \\")
print("     /   \\")
print("    /     \\")
print("   /       \\")
